const productos= [
    {
        id:1,
        foto:"image/aloe.jpg",
        nombre:"Aloe",
        categoria:"exterior",
        cantidad:1,
        precio:350
      },
      {
        id:2,
        foto:"image/jade.jpg",
        nombre:"Jade",
        categoria:"exterior",
        cantidad:1,
        precio:290
      },
      {
        id:3,
        foto:"image/lazo.jpg",
        nombre:"Lazos de familia",
        categoria:"interior",
        cantidad:1,
        precio:300
      },
      {
        id:4,
        foto:"image/palo.de.agua.jpg",
        nombre:"Palo de agua",
        categoria:"interior",
        cantidad:1,
        precio:400
      },
      {
        id:5,
        foto:"image/potus.jpg",
        nombre:"Potus",
        cantidad:1,
        precio:250
      },
      {
        id:6,
        foto:"image/sansevieria.jpg",
        nombre:"Sansevieria",
        categoria:"exterior",
        cantidad:1,
        precio:400
      },
      {
        id:7,
        foto:"image/wembe.jpg",
        nombre:"wembe",
        categoria:"exterior",
        cantidad:1,
        precio:400
      },
      
      {
        id:8,
        foto:"image/cactus1.jpg",
        nombre:"cactus",
        categoria:"cactus",
        cantidad:1,
        precio:200
      },
      {
        id:9,
        foto:"image/cactus2.jpg",
        nombre:"cactus",
        categoria:"cactus",
        cantidad:1,
        precio:270
      },

      {
        id:10,
        foto:"image/suculenta1.jpg",
        nombre:"suculenta",
        categoria:"suculenta",
        cantidad:1,
        precio:360
      },
      {
        id:11,
        foto:"image/suculenta2.jpg",
        nombre:"suculenta",
        categoria:"suculenta",
        cantidad:1,
        precio:205
      },
      {
        id:12,
        foto:"image/suculenta3.jpg",
        nombre:"suculenta",
        categoria:"suculenta",
        cantidad:1,
        precio:250
      }
]